### ISSUE TITLE
Free & Open Source data pack

### ISSUE THREAD

**Issue by neagix** [neagix/smw-next#1]
_smw_ needs a free and open source data pack that can be released without issues.
The data pack shall contain:
- tilesets
- sprites (a.k.a. skins)
- sounds
- music

Map compatibility with original smw shall be attempted, but it's not 100% necessary

This issue shall be closed after release of milestone 2.0 with a free and open source data pack

**Comment by Wharp** [comment]
I'm having a bit of trouble, where any time I make or edit a skin it can't be read by the program, even though I have tried everything I can think of to make my original skins be like the default ones. Moreover, I have tried to use a default skin that has worked before ingame, then after I edit just one pixel, it will not work.

Any ideas?

**Comment by Wharp** [comment]
Also, I can edit the tilesets just fine.

**Comment by neagix** [comment]
Ok, I have created issue https://github.com/neagix/smw-next/issues/3 I will update it when I look into this issue
