### ISSUE TITLE
Cannot edit skins

### ISSUE THREAD

**Issue by neagix** [neagix/smw-next#3]
As @Wharp reports, editing skins make it impossible to use them.

Will need to reproduce this with smw-next and then look for some CRC check somewhere

**Comment by Wharp** [comment]
I don't really have google talk, but irc works. Also I have Windows, it would be great if you compiled it for me! 

Date: Wed, 24 Jul 2013 23:13:59 -0700

**Comment by neagix** [comment]
of course! I am going to compile it, will publish the link :)

regarding IRC: we can use channel #supermariowar on freenode

**Comment by neagix** [comment]
@Wharp  can you reproduce this issue with the smw.exe I provided in https://github.com/neagix/smw-next/issues/4 ?
